### ISSUE TITLE
h3+h4 style adjustments

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#12]
"Skillset built...", "Shoot me an Email", "Social, Maybe?" and "Let's Have Lunch" texts should be assigned to a new style ('.h4') with style duplicated from current 'h3'.

Rest of the titles assigned to '.h3' should stay as they are, and the style itself should change to:
```
font-family: Effra-Medium;
font-size: 46px;
color: #494949;
letter-spacing: 0;
line-height: 45px;
```

All per original design.

**Comment by ranbena** [comment]
Updated. Close if ok.

**Comment by faderud** [comment]
The assignment of styles is correct.
Styles' definition is exactly the opposite :)
"Hafuch, Gutte"

**Comment by ranbena** [comment]
Fixed 🙃😅
