### ISSUE TITLE
Sticky text sections on the left

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#13]
When scrolling, the texts of the design showcases shouldn't scroll with the page but rather fade in/out when the scroll reaches certain points.

The only exception is the EvMe showcase, where logo and business cards' texts should join the main text instead of replacing it.

Irrelevant for mobile
Not in MVP.

**Comment by ranbena** [comment]
@faderud I whipped up quick demo of a simpler implementation of sticky elements.
Wdyt?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/486954/84587612-5ae3eb80-ae29-11ea-90f7-523b30460d49.gif)

**Comment by faderud** [comment]
@ranbena I love it! That was the exact intention of the initial design, and you have nailed it perfectly!
