### ISSUE TITLE
Animate center word in the header

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#15]
**Basic animation definition to start with and finalize later:**
- Word 1 stays for 4 seconds
- Word 1 fades out to alpha 0 with ease in+out and moves 20px to the right. Animation length: ~200ms
- At the ~100ms mark of the above animation, Word 2 fades in from alpha 0 to 100, ease in+out, starting with x-20px of its final position. Animation length: ~300ms
- Repeat

**Words array:** Human, Authentic, Trustworthy, Sensitive
Please make it easy for me to add/remove words without messing up the animation.

I'm marking it MVP not only because I'm a greedy pig, but also because it's important for me to emphasize these values.

**Comment by ranbena** [comment]
🐽

**Comment by ranbena** [comment]
Done 🔥

<img src="https://user-images.githubusercontent.com/486954/55581712-433dad00-5726-11e9-9d81-97f1ca03c00e.gif" width="300" />

Ril ezpz to change.

index.html
```html
<h1>
  I Create
  <em>Human</em> <em>Authentic</em> <em>Trustworthy</em> <em>Sensitive</em>
  <br /><br />
  Experiences.
</h1>
```
styles.css
```css
#main h1 em {
  --item-count: 4;
  --anim-duration: 4.4s;
  --anim-translate-x: 20px;
```

The animation transition timing is a bit hard make precise (percentage instead of time units) but I think it looks close to what you described.

**Comment by ranbena** [comment]
The 1st word starts animation in - do you want it to start static?

**Comment by ranbena** [comment]
In mobile I made it transition 10px instead of 20px cuz it looked exaggerated.

**Comment by faderud** [comment]
>The 1st word starts animation in - do you want it to start static? ...

@ranbena it should be static just as it is now. Perfect!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ranbena** [comment]
> @ranbena it should be static just as it is now. Perfect!

I'm confused. It's not static right now.
When the page loads, "Human" starts hidden and then animates in.

**Comment by ranbena** [comment]
Ok, I found a way to make it start static. Updated.

**Comment by faderud** [comment]
@ranbena let's change to 2.5 secs. If it still won't work - I'll change it by myself after launch.

**Comment by ranbena** [comment]
Np. Updated.
