### ISSUE TITLE
Add favicon and webclip + change page title

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#16]
@ranbena please add favicon.png and webclip.png to the code, both are in the assets folder on Dropbox.

In addition, please change the page title to "Fade Rudnitsky - I Create Human Experiences."

Thanks

**Comment by ranbena** [comment]
Done.

#### Favicon
![Screen Shot 2019-04-06 at 11 48 43](https://user-images.githubusercontent.com/486954/55667215-11316580-5862-11e9-91a0-0cb235515599.png)

#### Webclip
<img width="326" alt="Screen Shot 2019-04-06 at 11 49 04" src="https://user-images.githubusercontent.com/486954/55667216-11316580-5862-11e9-8157-a0de80d5d061.png">
