### ISSUE TITLE
Lazy load image under the fold

### ISSUE THREAD

**Issue by ranbena** [faderud/faderud.github.io#22]
The website loads a lot of heavy image which hinder the initial loading experience (I always see @faderud's head disembodied till everything loads...)

### Guess wat?!
A [new capability](https://groups.google.com/a/chromium.org/forum/m/#!topic/blink-dev/jxiJvQc-gVg) is about to be published in Chrome (majority of humanity usage) which does exactly that! Doesn't need any code change. It's probably just gonna be enabled by default 😁

**Comment by faderud** [comment]
Yup, I read about that earlier today. Yippies!

**Comment by ranbena** [comment]
Basically, gotta put `loading=lazy` on each `img` element in the page.

**Comment by faderud** [comment]
Will not fix.
