### ISSUE TITLE
1/3: Add 1024px-width resolution support

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#23]
Adding support for 1024px-wide screens will optimize the website for smaller laptops, as well as for tablets in landscape mode

**Mock:**
 "1024" on [Zeplin](https://zpl.io/bAB6MPn)

**Layout Logic**
This layout is based on the regular website, with the following changes:
- `.h1` CSS style - created .h1-1024 in Sketch in Zeplin with the following changes:
   - Text size changed from 100px to 80px
   - Line spacing changed from 86 to 68 (if you didn't configure it initially, maybe leaving it as it is will work too, try before changing)
- `.h2` CSS style - created .h2-1024 in Sketch in Zeplin with the following changes:
   - Text size changed from 70px to 56px
- `.h4` CSS style - created .h4-1024 in Sketch in Zeplin with the following changes:
   - Text size changed from 36px to 29px
- The main visual element (headshot and the green background) scaled down to 80% of its original size
- EvMe items rearranged differently
- Screen margins changed

**Comment by faderud** [comment]
1. "Scroll to Begin" locks its position together with the menu and stays on the screen throughout the entire scroll. Should fade out. (Safari only, @ranbena )
![UNADJUSTEDNONRAW_thumb_2f9f](https://user-images.githubusercontent.com/5468984/60399853-160d6900-9b74-11e9-8355-2c6f7f61be9d.jpg)
2. Hero frame gets messed up because of misaligned image and background
3. Menu and "Scroll to Begin" are off the frame (Safari only, @ranbena )
![UNADJUSTEDNONRAW_thumb_2fa0](https://user-images.githubusercontent.com/5468984/60399866-68e72080-9b74-11e9-9971-666e305fd227.jpg)
4. Alignment of all screenshots except the first one in the last section is messed up
![UNADJUSTEDNONRAW_thumb_2f9d](https://user-images.githubusercontent.com/5468984/60399873-77cdd300-9b74-11e9-9ae6-11971ca19958.jpg)
5. A minor horizontal scroll is possible, creating a weird gap on the right.

**Comment by ranbena** [comment]
On which device are these found?

**Comment by faderud** [comment]
iPad Mini (1024x768). Most of them happen on both Safari and Chrome.

**Comment by ranbena** [comment]
> 2. Hero frame gets messed up because of misaligned image and background
> 3. Menu and "Scroll to Begin" are off the frame

Fixed.

The rest are unreproducible in current iOS. I tend to blame your mini v1  😬
So I'll leave it be.
