### ISSUE TITLE
2/3 Add landscape layout for mobile

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#24]
Adding support for landscape orientation on mobile devices will do exactly that, plus will lay the grounds for the tablet portrait mode

**Mock:**
 "Mobile Landscape" on [Zeplin](https://zpl.io/bAB6MPn)

**Layout Logic**
This layout is based on the portrait mobile version, with the following changes:
- Main section alignment is more similar to the desktop version (aligned side by side instead of one under another
- Skillset bullets are divided into two columns
- All titles where the company name used to appear after a line break are now merged into the same line
- All web screenshot enlarged to fit within the new margins (might want to use the higher-res assets from the desktop version)
- EvMe assets' alignment changed. Again.
- Social section moved to be on the right of "shoot me an email" section instead of lay beneath it
- "Make it Happen" button in the "Let's Have Lunch" section now gets to full available width within the margins.

**Comment by ranbena** [comment]
@faderud I made the bullet list layout a bit different cause it was easier:

<img width="400" src="https://user-images.githubusercontent.com/486954/60170605-6ea9d280-9811-11e9-9c92-14af6067f19e.png">

**Comment by faderud** [comment]
Looks great!
One small fix @ranbena :
Body text of the sections is not consistent in size. In some of them, it's bigger and in some it's normal.

**Comment by ranbena** [comment]
> Body text of the sections is not consistent in size. In some of them, it's bigger and in some it's normal.

Fixed!
