### ISSUE TITLE
3/3 Add tablet portrait layout

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#25]
Adding a portrait tablet layout completes the set of resolutions and screen I'd like to support at this stage.

**Mock:**
 "768" on [Zeplin](https://zpl.io/bAB6MPn)

**Layout Logic**
This layout is almost identical to the [Mobile Landscape layout](https://github.com/faderud/faderud.github.io/issues/24), with the following exceptions:
- It uses text styles from the [1024px version](https://github.com/faderud/faderud.github.io/issues/23)
- The "scroll to begin" _does_ show
- Unlike in the mobile version, the "visit" button in Neura Dev section as well as "Project Shut Down in 2015" button in EvMe section _do_ appear.
- All web screenshots take the full width within the margins.
- "Make it Happen" button in the "Let's Have Lunch" section has regular width.

**Comment by faderud** [comment]
Looks so much better!
A few issues:

1. "Scroll to Begin" locks its position together with the menu and stays on the screen throughout the entire scroll. Should fade out.
![UNADJUSTEDNONRAW_thumb_2f9f](https://user-images.githubusercontent.com/5468984/60399853-160d6900-9b74-11e9-8355-2c6f7f61be9d.jpg)
2. Footer has escaped the frame. Catch it before it runs away!
![UNADJUSTEDNONRAW_thumb_2f9e](https://user-images.githubusercontent.com/5468984/60399852-0beb6a80-9b74-11e9-8548-f613c05f53ff.jpg)
3. All image resources used have very poor quality. Are we using the best bucket possible? Looks OK in landscape orientation.
![UNADJUSTEDNONRAW_thumb_2f9c](https://user-images.githubusercontent.com/5468984/60399849-fbd38b00-9b73-11e9-99cb-b78556cf8e69.jpg)

**Comment by ranbena** [comment]
> "Scroll to Begin" locks its position together with the menu and stays on the screen throughout the entire scroll. Should fade out.

Can't repro. Same as before - probably an older iOS problem. Leaving as is.

> Footer has escaped the frame. Catch it before it runs away!

Caught it!

> All image resources used have very poor quality. Are we using the best bucket possible? Looks OK in landscape orientation.

Should be ok now. Check it.
