### ISSUE TITLE
Fix scroll appearing on iPad when tabs are present

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#30]
In Safari on the iPad, when more than one tab is present (and therefore the tab bar is open), the scroll appears again, since the footer gets cut off.

**Comment by ranbena** [comment]
Which iPad is it? (what screen dimensions?)

**Comment by faderud** [comment]
iPad 6th gen.
The resolution is 1536 × 2048 (retina of 768x1024).
Happens on both landscape and portrait in Safari, when tabs are present.
The tabs seem to be stealing another 33px (66 on retina).
![IMG_0016](https://user-images.githubusercontent.com/5468984/80301966-e5a45480-87af-11ea-8136-a3dc9c7791bf.PNG)

**Comment by ranbena** [comment]
Try it now at https://ranbena.github.io/faderud.github.io

**Comment by faderud** [comment]
Worked like a charm! Thanks! Please create a PR. Closing this issue.
