### ISSUE TITLE
Update main image on faderud.com homepage

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#34]
**So... we're updating the main image on faderud.com homepage.**
Unlike the current one, the new one is used as a background image, requiring some CSS changes to position it well on all resolutions as well as some color tweaks for the content itself.

💎 **Updated Sketch file, containing all changes is [here](https://www.dropbox.com/s/0vzswm3cebqhcv3/FadeRudnitsky.com%20website%20v05.sketch?dl=0)**

**Changes required:**
- [ ] Update the actual image and its positions through resolutions
- [ ] Update text colors
- [ ] Update button colors (normal, hover and pressed states)

Thank you, kind sir 🙏🏼

**Comment by ranbena** [comment]
@faderud perhaps also prepare updated favicon/webclip/social_meta_image?

**Comment by faderud** [comment]
@ranbena you're right. Updated the favicon, webclip, and the social image. Please download the updated Sketch file from the same link again.
