### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by ranbena** [faderud/faderud.github.io#4]
Needs implementing.

**Comment by ranbena** [comment]
@faderud I whipped up a mobile version.
Requires more work on the content images but the main concerns (navigation, spacing, sizes) are looking good. Lmk what you think.

![Screen Shot 2019-04-03 at 9 10 39](https://user-images.githubusercontent.com/486954/55456787-9ad9fc80-55f0-11e9-8ad4-3b9f26e20ea2.png)

**Comment by ranbena** [comment]
@faderud I think the mobile version should load dedicated content images that are more fitting for a mobile screen and context.
For instance, portrait mode images in two columns, so a screen could fit 4 instead of 1.

**Comment by faderud** [comment]
Nice! A few things I have noticed immediately:
- The menu should be aligned to the right
- Paragraph font (light) is too light, perhaps we should use regular weight for mobile users
- Images are messed up, I'll re-align them in Sketch first.
- I'll work on updated settings for the headings to looks better and will send over.

**Comment by faderud** [comment]
- Email button stays "clicked" when switching back from the email client to the browser. Happens on mobile only (both Safari and Chrome)

**Comment by ranbena** [comment]
Landscape mode main image aligns to left instead of right.

**Comment by ranbena** [comment]
- [x] The menu should be aligned to the right
- [x] Paragraph font (light) is too light
- [x] Landscape mode main image aligns to left instead of right.
- [x] Email button stays "clicked"

**Comment by faderud** [comment]
@ranbena I have added the mobile layout to Zeplin:
https://app.zeplin.io/project/5ca2ffb09972713e00419380/screen/5ca5ae5d561e75a1fdea0bfe
And the menu on scroll:
https://app.zeplin.io/project/5ca2ffb09972713e00419380/screen/5ca5ae5d300c1ba055e5b9a3

Working on exporting mobile assets now. Should there be x1,x2, and x3 versions?

**Comment by ranbena** [comment]
> Working on exporting mobile assets now. Should there be x1,x2, and x3 versions?

I'd go for 2x but 3x if the difference in weight is negligible.
Make the jpeg quality as low as you can - it's mostly unnoticeable when sized down and on small screens.

**Comment by faderud** [comment]
Mobile assets are here:
https://www.dropbox.com/sh/8193avpe8xtszbw/AACZnf2pl-IQ_LQ7AAwe4_Gja?dl=0

**Comment by faderud** [comment]
@ranbena note that in the mobile version I've hidden the inline buttons for Neura and EvMe projects.

**Comment by faderud** [comment]
@ranbena Any ETA for the mobile version layout?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ranbena** [comment]
Eta tonight

**Comment by faderud** [comment]
![giphy](https://user-images.githubusercontent.com/5468984/55631452-bbf14780-57c0-11e9-8711-135f129ce9e3.gif)

**Comment by faderud** [comment]
@ranbena, corrected FirefoxOS image to be a single image.
Please remove all files and instances and resolutions of:
* firefox_mobile
* evme_firefoxos_mobile_mobile
* evme_mobile1_mobile

Replace with:
* `evme_firefoxos_mobile.png`, `evme_firefoxos_mobile@2x.png`, `evme_firefoxos_mobile@3x.png` 
They're slightly heavy, but it's OK. Already optimized their size as much as I could. All in Dropbox

Note that I had to save it with the shadows so no CSS shadows needed there.

**Comment by ranbena** [comment]
evme_firefoxos_mobile@2x.png?subject=I'm%20sending%20an%20email%20to%20an%20image

**Comment by faderud** [comment]
EDIT: I got it. It's the @ sign...

*Scratching my head*
No idea what happened there
But you got the idea

**Comment by ranbena** [comment]
Content and many mobile adjustments updated.

Notice there are 2 missing image sizes in assets (cards 1 and 3)

**Comment by faderud** [comment]
Added missing images to Dropbox

**Comment by faderud** [comment]
@ranbena There’s a missing space in this section:
![GitHawk Upload by faderud](https://i.imgur.com/QXa7T2b.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ranbena** [comment]
Updated.

@faderud I'm gonna close this and do a joint fixing session if needed.
