### ISSUE TITLE
Layout is messed up on tablet landscape

### ISSUE THREAD

**Issue by faderud** [faderud/faderud.github.io#44]
![IMG_AA09F4D310C6-1](https://user-images.githubusercontent.com/5468984/106151346-ee81e680-6184-11eb-91cc-e298b624afc0.jpeg)

There's a layout issue that seems to happen when looking at the website on a landscape of a tablet (iPad, in my case). I can't seem to reproduce it when using Safari on the Mac with the exact same window size.

Any ideas?

**Comment by ranbena** [comment]
@faderud Can you hunt down the version in which it started?

**Comment by faderud** [comment]
@ranbena the only thing I know with 99% certainty is that the issue didn’t exist on this commit: https://github.com/faderud/faderud.github.io/tree/322decaae20c3486b9e1bb5ea80e5b2f98c0fc3f
Is there a way to preview actual commits as rendered pages?

**Comment by faderud** [comment]
According to the wayback machine, it seems that on Dec 31st. there was a similar issue except that the content shifted in a different direction 
![7324004B-39DA-4BDF-9EF1-0FB2F219B073](https://user-images.githubusercontent.com/5468984/106159922-fabe7180-618d-11eb-8cdf-14011818b975.png)

**Comment by ranbena** [comment]
Ok, I got an idea on how to re-implement this in a simpler and bulletproof way. Stay tuned!
