### ISSUE TITLE
Update footer mailto buttons

### ISSUE THREAD

**Issue by ranbena** [faderud/faderud.github.io#6]
I put placeholders for subject and body.

**Comment by faderud** [comment]
Shoot me an email:
Subject: "Hey%2C%20I'm%20coming%20from%20your%20website"
Body: empty

Lunch
Subject: "Let's%20have%20lunch!"
Body: "Hey%2C%20Fade!%0A%0AI'd%20like%20to%20discuss%20the%20following%20stuff%20with%20you%20over%20lunch%3A%0A"

Both should send to fade@faderud.com

**Comment by ranbena** [comment]
Updated
