### ISSUE TITLE
Complete project content 

### ISSUE THREAD

**Issue by ranbena** [faderud/faderud.github.io#8]
Evme and web content.

**Comment by ranbena** [comment]
@faderud evme_businesscard@2x.jpg and evme_logo@2x.jpg are saved as jpgs with white bg.
Should either be a transparent png or saved with the site bg color.

**Comment by faderud** [comment]
@ranbena replaced with transparent PNG on Dropbox (jpg doesn't promise that the background will match)

**Comment by ranbena** [comment]
Updated.
