### ISSUE TITLE
Scroll indicator animation

### ISSUE THREAD

**Issue by ranbena** [faderud/faderud.github.io#9]
Added a "hover" animation to the scroll indicator.

Animation spec:
* From top (-2px) to bottom (+2px).
* 1s duration
* Ease- in +out

Additional feature:
* After scroll animation stops.

**Comment by ranbena** [comment]
@faderud it's live on https://ranbena.github.io/faderud.github.io

Lemme know if you wanna tweak the animation.

**Comment by faderud** [comment]
Fab!
Only the arrow should move. Animation speed and easing look perfect.
Let's change top/bottom to -5px/+5px so that it stands out more

**Comment by ranbena** [comment]
Updated.

**Comment by faderud** [comment]
Great! Two more things and we're done with it:
1. More the text 5px to the right (it looks too close to the arrow now)
2. Fade out this whole element when the menu appears for the first time, and never fade it back in (until refresh, of course).

**Comment by ranbena** [comment]
Done

**Comment by faderud** [comment]
Perfecto!
